//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer(int number, int assembledYear, string building, int roomNo)
        {
            Number = number;
            AssembledYear = assembledYear;
            Building = building;
            RoomNo = roomNo;
            
        }

        public int Number { get; set; }
        public int AssembledYear { get; set; }
        public string Building { get; set; }
        public int RoomNo { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
